### ISSUE TITLE
[Suggestion] Portable version for Windows x86/64

### ISSUE THREAD

**Issue by GATOQSECOMIO** [Sudo-Rahman/Iridium#4]
Is it possible to create a portable version?

This is an amazing project, congrats!
PD: Sorry for my bad english.

Thank You.

**Comment by Sudo-Rahman** [comment]
Do you want zip version ?

**Comment by GATOQSECOMIO** [comment]
> Do you want zip version ?

Yes, this issue is solved. Thanks.
