### ISSUE TITLE
Failed to create file system for...

### ISSUE THREAD

**Issue by GATOQSECOMIO** [Sudo-Rahman/Iridium#5]
Error : 2023/06/13 16:21:30 Failed to create file system for "CloudName:": didn't find section in config file

Unable to access cloud content.

rclone.conf file is imported from other app ([MinorMole/RcloneBrowser-Portable](https://github.com/MinorMole/RcloneBrowser-Portable))

**Comment by Sudo-Rahman** [comment]
try deleting rclone conf and restart iridium for a new configuration

**Comment by GATOQSECOMIO** [comment]
> try deleting rclone conf and restart iridium for a new configuration

Thanks for the support and Sorry for the delayed response.

I have tried to create an account without having the file imported (rclone.conf), from a completely fresh installation of Iridium.
From the graphical interface I have proceeded to create three accounts (Onedrive, Dropbox and Mega), the first two accounts do not show anything when pressing the "log in" button (Iridium does not react but you can continue using it, it does not freeze), the third account (Mega) throws me to the desktop with a Windows error event (Application error: ID:1000).

I attach an example image. I have used my email and username on all three accounts but end up with the results explained above.

![2023-07-14 02_26_20-Window](https://github.com/Sudo-Rahman/Iridium/assets/19736343/9efadb26-6820-4634-91ec-b9ed58952a98)

OS : Windows 10 LTSC 2019 / Iridium 0.8.9 (Portable/zip)
Sorry for my bad english.

**Comment by Sudo-Rahman** [comment]
There was indeed a problem with the connection to mega which has been resolved, however no problem on my side for the connection to onedrive and dropbox.
